### ISSUE TITLE
Download-Link for all Assets in the Asset Store (Offline-Usage of assets in asset store)

### ISSUE THREAD

**Issue by Rick978** [4ian/GDevelop-documentation#13]
Hello,

we are planning to do a youthcamp, where we want to use GDevelop, for first game programming experience. Unfortunately the internet connection there, is really bad and awful. 

Is it possible to download all the great resources of the "GDevelop Asset Store", that we can provide the ressources without internet connection? 

Is there a download link or Github Repo available?

Thanks for this very great Software! GDevelop is awesome for young people, love it!! 👍

**Comment by 4ian** [comment]
Thanks for reaching out :) Unfortunately no easy solution and there probably won't be one as the "asset store" is meant to be expanded and could be very large. But I suggest you could go through a few dozens/hundreds resources and download them and provide them as a starting point during the youthcamp?

Better, just grab the free, public domain assets from artists like Kenney.nl: https://www.kenney.nl/
If you provide them in a folder, along with the desktop version of GDevelop, you have way enough to do tons of games :)

**Comment by Rick978** [comment]
Thanks for your super fast response! I downloaded some resources and watched some tutorials how to import. 

You are right, there are many assets available.

Thanks for help! :)
